version: '3'

services:
  web:
    container_name: proxitok-web
    image: ghcr.io/riqalter/proxitok:latest
    ports:
      - 8080:80
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_SIGNER=remote
      - API_SIGNER_URL=http://proxitok-signer:8080/signature
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - redis
      - signer
    networks:
      - proxitok

  redis:
    container_name: proxitok-redis
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - proxitok
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev

  signer:
    container_name: proxitok-signer
    image: ghcr.io/riqalter/signtok:latest
    networks:
      - proxitok

volumes:
  proxitok-cache:

networks:
  proxitok:
